CREATE TABLE USERS
(
    ID                 BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME               VARCHAR(255),
    ENCRYPTED_PASSWORD VARCHAR(255),
    EMAIL              VARCHAR(255),
    PHONE              VARCHAR(20),
    CUSTOMER_STATUS    VARCHAR(20),
    COUNTRY_ID         BIGINT
) ENGINE = MYISAM;

ALTER TABLE USERS
    ADD CONSTRAINT FK_USER_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID);

CREATE TABLE COUNTRIES
(
    ID           BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE        VARCHAR(100),
    PHONE_PREFIX VARCHAR(10)
) ENGINE = MYISAM;

CREATE TABLE INTERESTS
(
    ID                   BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE                VARCHAR(255),
    INTEREST_AREA_STATUS VARCHAR(15)
) ENGINE = MYISAM;

CREATE TABLE POSTS
(
    ID               BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE            VARCHAR(255),
    DESCRIPTION      VARCHAR(2048),
    INTEREST_AREA_ID BIGINT,
    COUNTRY_ID       BIGINT,
    USER_ID          BIGINT
) ENGINE = MYISAM;

ALTER TABLE POSTS
    ADD CONSTRAINT FK_POST_INTEREST FOREIGN KEY (INTEREST_AREA_ID) REFERENCES INTERESTS (ID);
ALTER TABLE POSTS
    ADD CONSTRAINT FK_POST_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID);
ALTER TABLE POSTS
    ADD CONSTRAINT FK_POST_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

CREATE TABLE ROLES
(
    ID        BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255)
) ENGINE = MYISAM;


CREATE TABLE FK_USER_ROLE
(
    ID      BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (ID, USER_ID, ROLE_ID)
) ENGINE = MYISAM;

ALTER TABLE FK_USER_ROLE
    ADD CONSTRAINT FK_USER_ID_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
ALTER TABLE FK_USER_ROLE
    ADD CONSTRAINT FK_ROLE_ID_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID);


CREATE TABLE FK_COUNTRY_INTEREST
(
    ID          BIGINT NOT NULL AUTO_INCREMENT,
    COUNTRY_ID  BIGINT NOT NULL,
    INTEREST_ID BIGINT NOT NULL,
    PRIMARY KEY (ID, COUNTRY_ID, INTEREST_ID)
) ENGINE = MYISAM;

ALTER TABLE FK_COUNTRY_INTEREST
    ADD CONSTRAINT FK_COUNTRY_ID_COUNTRIES FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID);
ALTER TABLE FK_COUNTRY_INTEREST
    ADD CONSTRAINT FK_INTEREST_ID_INTERESTS FOREIGN KEY (INTEREST_ID) REFERENCES INTERESTS (ID);


CREATE TABLE FK_INTEREST_USER
(
    ID          BIGINT NOT NULL AUTO_INCREMENT,
    INTEREST_ID BIGINT NOT NULL,
    USER_ID     BIGINT NOT NULL,
    PRIMARY KEY (ID, INTEREST_ID, USER_ID)
) ENGINE = MYISAM;

ALTER TABLE FK_INTEREST_USER
    ADD CONSTRAINT FK_INTEREST_ID_INTERESTS FOREIGN KEY (INTEREST_ID) REFERENCES INTERESTS (ID);
ALTER TABLE FK_INTEREST_USER
    ADD CONSTRAINT FK_USER_ID_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID);