INSERT INTO USERS VALUES(1, 'Egor', '1234', 'email1@gmail.com', '+380931112233', 'ACTIVE', 1);
INSERT INTO USERS VALUES(2, 'Andrew', '123456', 'email2@gmail.com', '+380934445566', 'ACTIVE', 2);
INSERT INTO USERS VALUES(3, 'Vasya', '12345', 'email3@gmail.com', '+380937778899', 'ACTIVE',  3);

INSERT INTO COUNTRIES VALUES(1, 'Ukraine', '+380');
INSERT INTO COUNTRIES VALUES(2, 'Russia', '+7');
INSERT INTO COUNTRIES VALUES(3, 'Belarus', '+375');

INSERT INTO INTERESTS VALUES(1, 'IT', 'PUBLIC');
INSERT INTO INTERESTS VALUES(2, 'Oil and gas drilling', 'PUBLIC');
INSERT INTO INTERESTS VALUES(3, 'Dancing', 'PUBLIC');

INSERT INTO POSTS VALUES(1, 'Post about AI', 'Some text about AI', 1, 1, 1);
INSERT INTO POSTS VALUES(2, 'Post about Oil&Gas', 'Some text about Oil&Gas', 2, 2, 2);
INSERT INTO POSTS VALUES(3, 'Post about Folk Dances', 'Some text about Folk Dances', 3, 3, 3);

INSERT INTO ROLES VALUES(1, 'ROLE_ADMIN');
INSERT INTO ROLES VALUES(2, 'ROLE_CUSTOMER');

INSERT INTO FK_USER_ROLE VALUES(1, 1, 1);
INSERT INTO FK_USER_ROLE VALUES(2, 2, 2);
INSERT INTO FK_USER_ROLE VALUES(3, 3, 2);

INSERT INTO FK_COUNTRY_INTEREST VALUES(1, 1, 1);
INSERT INTO FK_COUNTRY_INTEREST VALUES(2, 2, 2);
INSERT INTO FK_COUNTRY_INTEREST VALUES(3, 3, 3);

INSERT INTO FK_INTEREST_USER VALUES(1, 1, 1);
INSERT INTO FK_INTEREST_USER VALUES(2, 2, 2);
INSERT INTO FK_INTEREST_USER VALUES(3, 3, 3);